### PR TITLE
Fixes #4

### LINKED ISSUE #4: Add suitable favicon to minimal mistakes jekyll theme
solving ```Favicon.ico not found```  in minimal mistake jekyll theme

```error```

```unexpected output```

possible solution:

https://github.com/mmistakes/minimal-mistakes/issues/949

https://ptc-it.de/add-favicon-to-mm-jekyll-site/

### PR DESCRIPTION
**Pull request by thebhavana**

### CODE REVIEW

**Comment by pavanjoshi914** [comment]
can you describe what changes you have made along with screenshots

**Comment by pavanjoshi914** [comment]
You cant push chnages for _site partial . it is automatically generated by jekyll by compiling remaining folder. doesnt make any sense , by making changes in _site folder. 

if there is any change to be don in theme's html you have to override theme defaults 
refer:: https://mmistakes.github.io/minimal-mistakes/docs/overriding-theme-defaults/

You can simply create directory strucutre as done here 
https://github.com/mmistakes/minimal-mistakes/tree/master/_layouts

in any html files in layout is to be edited then create _layout folder and put html file in it 
and make your own changes

**Comment by thebhavana** [comment]
It adds favicon . On reloading, code is missing and favicon also. 
Screenshot (2285)

**Comment by thebhavana** [comment]
Screenshot (2283)

It adds favicon. Can you check it @pavanjoshi914 

> If not working, I will make changes accordingly.

**Comment by pavanjoshi914** [comment]
what changes made this work? on which file and which line changes were needed? you pushed whole _site folder that's inappropriate to merge .

**Comment by thebhavana** [comment]
_site -> index.html -> line11 
All files must be uploaded, otherwise configuration changes.

**Comment by pavanjoshi914** [comment]
we have to take care of deploy too. I fixed this in fixed in 2be7d48e1edaf03bb710b96195b43cbde5b0e40d b78952b1ad5f1f27f01c19db47ceda67d2793914 8071a27f674738f2b91ca24caa5091ce95c656d6 

you can see how changes are made. this typically requires overriding theme defaults + proper use of liquid tags for generating right urls to favicons

image

**Pull request closed without merging**
